### ISSUE TITLE
Detailed installation / configuration instructions

### ISSUE THREAD

**Issue by jacmoe** [gka/schnack#30]
I am not a Node.js guy, so I need a bit more detailed instructions :)

So, I created Twitter and Github applications.

I did not provide a call-back URL for neither. Is that alright?

Also, what is the `secret` in the config's oauth section?

Do I need to provide keys/secrets for both pushover and webpush?

And, finally: after running `npm install`, I simply ran `node index.js` - and it complained that the keys/secrets for the pushover/webpush was in the wrong format.
After removing the section, it complained that pushover/webpush was unset.

Thanks in advance!

Oh, by the way: I have put Schnack in it's own subdomain, and I plan on running it as a service once it works.
I do need to run `node index.js` before embedding it on my site, right?

**Comment by jacmoe** [comment]
Also, Node version 0.8 - the highest version that my host supports.

**Comment by jacmoe** [comment]
When I run `npm server` it complains that that command doesn't exist, which is odd. At least to me, a Node.js n00b. :p

**Comment by g-div** [comment]
Hi @jacmoe, right now the installation could appear something complicated, but let's try:

> I did not provide a call-back URL for neither. Is that alright?

You should provide as callback the routes `/auth/twitter/callback` and `/auth/github/callback`. So if your schnack server is running on [example.com](example.com), the callback URLs should be `https://example.com/auth/twitter/callback` and `https://example.com/auth/github/callback`

> Also, what is the secret in the config's oauth section?

This is passed to [express-session](https://github.com/expressjs/session#secret).

> Do I need to provide keys/secrets for both pushover and webpush?
And, finally: after running npm install, I simply ran node index.js - and it complained that the keys/secrets for the pushover/webpush was in the wrong format.
After removing the section, it complained that pushover/webpush was unset.

You don't need both. It should work if you just use one of them. If you already have a pushover account, go for it. Otherwise you can just try to follow the [setup instructions](https://github.com/gka/schnack#push-notifications-for-new-comments) for webpush and let me here know if you encounter some problems.

> Oh, by the way: I have put Schnack in it's own subdomain, and I plan on running it as a service once it works.

This should work.

>  I do need to run node index.js before embedding it on my site, right?

Right!

> When I run npm server it complains that that command doesn't exist, which is odd.

The exact command is `npm run server`, since `server` is not one of npm's predefined commands (`start`, `stop`, `install`, etc.)

**Comment by jacmoe** [comment]
Thank you!
Now I should be able to get cooking - I'll let you know if I'm successful 😄

**Comment by jacmoe** [comment]
Since the installation instructions assume that you are familiar with Node.js and Express, should I create a pull request with more detailed, non-assuming, installation instructions appropriate for people who are not part of that world?

**Comment by g-div** [comment]
I will close this, feel free to reopen this (or create another issue) in case you still need some help.
I've included your request in #32

**Comment by jacmoe** [comment]
Thank you - I've been busy with NaNoWriMo (National Novel Writing Month) - I'll get back to you 😸
