### ISSUE TITLE
`getSchnackDomain()` only works for subdomains in `schnack_host`

### ISSUE THREAD

**Issue by janpio** [gka/schnack#41]
In #37 I tried to get Schnack working locally but encountered problems. But placing `console.log` throughout the code - like a professional - I could pin down the problem:

`getSchnackDomain()` only works with domains of the format `sub.example.org` configured in `schnack_host`:

https://github.com/gka/schnack/blob/master/src/helper.js#L74

With `localhost` this just returns an empty string, with `example.org` it returns `org`. 
For `sub.example.org` it returns `example.org`.

**Comment by gka** [comment]
so that's intended behaviour. the way schnack is set up right now the schnack server _has_ to run on the same domain as the site that's embedding schnack. the reason is that we're using cookie sessions that can only be shared across subdomains of the same root domain.

if you're just testing the setup on localhost, just configure schnack to run on something like http://schnack.localhost so the code in `getSchnackDomain` will work.

**Comment by janpio** [comment]
Ok.
